# Generated by Django 4.1.5 on 2023-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=50)),
                ('about_theater', models.TextField(blank=True, max_length=350)),
                ('landmark_1', models.CharField(max_length=50)),
                ('landmark_2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('district', models.CharField(choices=[('TVM', 'Trivandrum'), ('EKM', 'Eranakulam'), ('kZH', 'Kozhikode')], max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('postal_code', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=25)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
