# Generated by Django 4.1.5 on 2023-02-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theater', '0002_theaterseat'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('6:30 AM', '6:30 AM'), ('10:30 AM', '10:30 AM'), ('2:30 PM', '2:30 PM'), ('6:30 PM', '6:30 PM'), ('10:30 PM', '10:30 PM')], max_length=100)),
                ('date', models.DateField()),
                ('total_tickets', models.IntegerField(default=50)),
                ('is_tick_avail', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theaters')),
            ],
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sold', 'sold'), ('available', 'available'), ('selected', 'selected')], default='available', max_length=50)),
                ('price', models.FloatField(default=150)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.movieshow')),
                ('theater_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theaterseat')),
            ],
        ),
    ]
